/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package package1;

import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Statement;
/**
 *
 * @author Rico
 */
public class frameMain extends javax.swing.JFrame {

    static Connection connection;
    static String url;
    static Statement st;
    static ResultSet rs;
     public int search(String id,String name)
   throws SQLException, ClassNotFoundException{
    Class .forName("com.mysql.jdbc.Driver");
    url="jdbc:mysql://localhost:3306/isdb";
    connection = DriverManager.getConnection
    (url, "root","09322622931fckyou");
    st = connection.createStatement();
    rs=st.executeQuery
    ("Select * From reg_tbl Where id= '"+id+"'  "
      + "and fname = '" +name+ "'");
            if(rs!=null){
                return 1;
            }
            else{
                return 0;
            }
     }
     
    public frameMain() {
        initComponents();
        
        frameMain.this.setLocation(380,150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelPass = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textPassword = new javax.swing.JTextField();
        textUserName = new javax.swing.JTextField();
        textLastName = new javax.swing.JTextField();
        textUserId = new javax.swing.JTextField();
        textUserAddress = new javax.swing.JTextField();
        textEmailAddress = new javax.swing.JTextField();
        textContactNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 58, -1, -1));

        jLabel3.setText("First Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 80, 20));

        jLabel4.setText("Last Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 80, 20));

        jLabel5.setText("Address:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 80, 20));

        jLabel6.setText("Mobile No.:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 80, 20));

        jLabel7.setText("Email:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 80, 20));

        labelPass.setText("Password:");
        getContentPane().add(labelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, 20));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        jLabel9.setText("Student ID:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, 20));

        jLabel10.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel10.setText("Student Registration");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 170, 50));
        getContentPane().add(textPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 290, -1));
        getContentPane().add(textUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 163, -1));
        getContentPane().add(textLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 180, -1));
        getContentPane().add(textUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 290, -1));
        getContentPane().add(textUserAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 380, -1));

        textEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailAddressActionPerformed(evt);
            }
        });
        getContentPane().add(textEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 200, -1));
        getContentPane().add(textContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/package1/0design.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // TODO add your handling code here:
        int check=0;
        try {
            check = search(textUserId.getText(),
                    textUserName.getText());
        } catch (SQLException ex) {
           // Logger.getLogger(frameRegister.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(frameRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
if(check==1){
   try {
      if(textPassword.getText() == null ?
        "" == null : textPassword.getText().equals("")){
        JOptionPane.showMessageDialog(null, 
        "Password must contain value","System Message",
                JOptionPane.INFORMATION_MESSAGE);
        textUserAddress.setText(null);
        textUserId.setText(null);
        textUserName.setText(null);
        textContactNumber.setText(null);
        textLastName.setText(null);
        textPassword.setText(null);
        textEmailAddress.setText(null);
        labelPass.setForeground(Color.red);
        }
  if((textUserId.getText() == null ? "" == null :
      textUserId.getText().equals("")) ||
      (textUserName.getText() == null ? "" == null :
      textUserName.getText().equals(""))){
      JOptionPane.showMessageDialog(null, 
      "ID and Name is Required","System Message",
              JOptionPane.ERROR_MESSAGE);
                }
                else{
                    st.executeUpdate("Insert into reg_tbl("
                   + "Id," + "password," + "fname,lname,address,mobileno,email"
                             + ") VALUES ('"
                            + textUserId.getText() + "','"
                            +textPassword.getText()+  "','"
                            + textUserName.getText() + "','"
                            + textLastName.getText() + "','"
                            + textUserAddress.getText() + "','"
                            + textContactNumber.getText() + "','"
                            + textEmailAddress.getText() + "')");
                            
                    JOptionPane.showMessageDialog(null, "Record Created",
                            "System Message",JOptionPane.INFORMATION_MESSAGE);
                    textUserId.setText("");
                    Update studentInfo= new Update();
                    studentInfo.setVisible(true);
                    frameMain.this.setVisible(false);
                }
            } catch (SQLException ex) {
               // Logger.getLogger(frameMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, 
                        "Record Already Exist","System Message",
                        JOptionPane.ERROR_MESSAGE);
            textUserAddress.setText(null);
            textUserId.setText(null);
            textUserName.setText(null);
            textContactNumber.setText(null);
            textLastName.setText(null);
            textEmailAddress.setText(null);
            textPassword.setText(null);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailAddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelPass;
    private javax.swing.JTextField textContactNumber;
    private javax.swing.JTextField textEmailAddress;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textPassword;
    private javax.swing.JTextField textUserAddress;
    private javax.swing.JTextField textUserId;
    private javax.swing.JTextField textUserName;
    // End of variables declaration//GEN-END:variables
}
